version: '3.5'

services:
    django:
        build:
            context: ../../
            dockerfile: configs/Docker/django/Dockerfile
        command: ./configs/Docker/bin/django-run.sh
        # providing the build and the image directive automatically tags the image
        # automatic tagging is performed with environment variables provided
        # through the Makefile and results in a tag with either a git commit hash
        # or a datetime stamp (see Makefile.deployment)
        image: ${DPS_BUILD_NAME_PREFIX}/django:${DPS_BUILD_ID}
        expose:
            - "8000"
    nginx:
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        # providing the build and the image directive automatically tags the image
        # automatic tagging is performed with environment variables provided
        # through the Makefile and results in a tag with either a git commit hash
        # or a datetime stamp (see Makefile.deployment)
        image: ${DPS_BUILD_NAME_PREFIX}/nginx:${DPS_BUILD_ID}
        ports:
            - "80:80"
