version: '3.5'

services:
    django:
        build:
            context: ../../
            dockerfile: configs/Docker/django/Dockerfile
        # this should *magically* include a hash/datetime/unique identifier
        image: ${DPS_BUILD_NAME_PREFIX}/django:${DPS_BUILD_ID}
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
